# Generated by Django 4.2.2 on 2023-06-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_recomender", "0002_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useritemmatrix",
            name="interaction",
            field=models.IntegerField(default=0),
        ),
    ]
