# Generated by Django 4.2.2 on 2023-07-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_recomender", "0004_basket"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_authenticated",
            field=models.BooleanField(default=False),
        ),
    ]
