# Generated by Django 4.2.2 on 2023-07-14 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("shop_recomender", "0007_remove_user_is_active_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="registration_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
