# Generated by Django 4.2.2 on 2023-07-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_recomender", "0008_alter_user_registration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
